# Welcome to Jekyll!
#

# Site settings
title: Portfolio
description: |
  Vince 't Hoen
owner: Vince 't Hoen # or company name
first_published: 2012 # if migrating another site, the year of your first publish
email: Vthoen@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Vincethoen
  #github: https://github.com/<username>
  linkedin-square: https://nl.linkedin.com/in/vince-t-hoen-b0023a119
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<vthoen@gmail.com>
  email: mailto:Vthoen@gmail.com?subject=WE WANT YOU!&message="

  #flickr:
  #instagram:
  #youtube-square:
  spotify: https://open.spotify.com/user/vthoen
  steam: http://steamcommunity.com/profiles/76561198106926306
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
